name:                example-socket-protobuf-server
version:             0.1.0.0
github:              "githubuser/example-socket-protobuf-server"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/example-socket-protobuf-server#readme>

dependencies:
- base >= 4.7 && < 5
- proto-lens
- proto-lens-protoc
- proto-lens-runtime
- network
- bytestring
- lens
- microlens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  example-socket-protobuf-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - example-socket-protobuf-server

tests:
  example-socket-protobuf-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - example-socket-protobuf-server
    - proto-lens
    - proto-lens-runtime
    - network
    - bytestring
    - lens
    - microlens
